Update main.yml
Updated the file path for the raw data file within repo

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -41,7 +41,7 @@ jobs:
 
       - name: Verify data file exists
         run: |
-          test -f "data/Ecommerce_Consumer_Behavior_Analysis_Data.csv" || (echo "Missing data CSV" && exit 1)
+          test -f "data/raw/Ecommerce_Consumer_Behavior_Analysis_Data.csv" || (echo "Missing data CSV" && exit 1)
 
       - name: Run EDA / Plot / Model
         run: |
